### ISSUE TITLE
Supporting numeric values for checkboxes

### ISSUE THREAD

**Issue by kevinhikaruevans** [vitalets/angular-xeditable#126]
Would it be possible to support numeric values 0/1s for `editable-checkboxes`? The reason I'm using numbers is because MySQL returns back booleans values with a 0/1 value. Right now, it seems like it only will accept hard boolean values instead of truthy/falsey values.

**Comment by nmstoker** [comment]
@kevinhikaruevans - not sure if you found a way to fix this yourself, but after some fiddling I managed a simple work around to make it okay.

If I've understood correctly then the issue was that upon the transition to the display of the actual checkbox the checkbox's initial setting does not respecting the initial model value (of 0 or 1), it's just blank whether the model is set to 1 or 0.

The logical test (ie **{{model.field == 1 ? 'Active' : 'Inactive'}}**) for displaying the text works fine, but as soon as the user clicked to edit the row then the checkbox appears incorrectly set.

I appreciate this workaround might not be acceptable for everyone, but I found that simply casting the MySQL output to be text worked. It's as simple as changing the output **Active** to be **CAST(Active AS CHAR)**.

**Comment by davidrothschild** [comment]
I was having this same issue -- my checkbox is tied to a Boolean in MySQL, which returns the value as Integer 0 or 1.  Tried @nmstoker 's suggestion to CAST it as CHAR, which I confirmed returned the value as String "0" or "1" instead of an Integer, but it still wasn't working for me.... 

I ended up leaving it as an Integer and adding **e-ng-checked="model.field"**, in addition to **e-ng-true-value** and **e-ng-false-value**, which DID work for me:

```
<span editable-checkbox="model.field" e-name="field" e-form="myform" e-ng-true-value="1" e-ng-false-value="0" e-ng-checked="model.field">
	{{model.field == 1 ? 'Yes' : 'No'}}
</span>
```

**Comment by roshenpo007** [comment]
<span editable-checkbox="model.field" e-name="field" e-form="myform" e-ng-true-value="1" e-ng-false-value="0" e-ng-checked="model.field">
    {{model.field == 1 ? 'Yes' : 'No'}}
</span>

Checked vene for value  0 also. Tried with above code.

**Comment by LewisCooper4** [comment]
Not sure if there was a definitive solution to this or not with the casting, but I think I found a solution that only requires html.  If you would prefer to not change how the SQL query returns the value then the solution is to make the e-ng-true-value=" '1' " (no spaces they are there to see the single quotes).  This way you can leave your SQL query intact (in case you don't have control over it) and you can handle this situation on the front end and not on the backend.

**Comment by tcledford3** [comment]
@davidrothschild  @roshenpo007 I have it working with the checkbox SQL field as VARCHAR and using @davidrothschild 's solution with the exception: **e-ng-checked="{{model.field}}"** instead of e-ng-checked="model.field". I hope this helps.

**Comment by tcledford3** [comment]
@davidrothschild @roshenpo007 Oops!  I thought I had it working. I ended up with the SQL field as an INT. And the HTML markup for my app is as follows:
<span editable-checkbox="data.active" e-name="active" e-form="rowform"
	        e-ng-true-value="'1'" e-ng-false-value="'0'" e-ng-checked="{{data.active}}">
    		{{data.active == 1 ? 'Yes' : 'No'}}  
	        </span>
This is working for me now. Sorry if my previous answer was confusing. It confused me too :)

**Comment by ckosloski** [comment]
@eugef This issue looks answered, please close
