### ISSUE TITLE
label + input[editable-text] = can't cancel

### ISSUE THREAD

**Issue by enapupe** [vitalets/angular-xeditable#250]
http://jsfiddle.net/NfPcH/6643/

If you use a input with editable-text and it is under a label, it won't cancel..

**Comment by enapupe** [comment]
Would you make a release so we can use the latest version on with bower?

**Comment by Painyjames** [comment]
Sure!
I need to have a look a the rest of the pull requests, but will try to have it done maybe this weekend?

**Comment by enapupe** [comment]
Cool, thanks!

**Comment by Painyjames** [comment]
Unfortunately I needed to change this commit (https://github.com/enapupe/angular-xeditable/commit/68cbb66a442f637661ea06b9a0f4a805d907bf20) since it was causing another issue (#262).

Might to have a look again at it having in mind this fiddle (https://jsfiddle.net/NfPcH/7191/). I'll try as well if I got any time.

Cheers!
