### ISSUE TITLE
Datepicker not opening when isOpen is true

### ISSUE THREAD

**Issue by SDries** [vitalets/angular-xeditable#310]
Hello, when I edit a date using the datepicker and then access the date again the datepicker doesn't show when i click the input field.
Please view [my plunker repro](http://plnkr.co/edit/BlgjKS85mPk36jeHlzg9?p=preview)

Steps to reproduce:
1. Click the link (datepicker appears)
2. Edit the date or just close the x-editable input
3. Click the link again (datepicker appears)
4. Click the text input, the datepicker disappears and doesn't reappear when i click the input

When debugging the ui-bootstrap-tpls.js I noticed that in the directive for the datepicker the `element[0]` was not the same as `event.target` in the documentClickBind function.
```javascript
var documentClickBind = function(event) {
  if (scope.isOpen && event.target !== element[0]) {
    scope.$apply(function() {
      scope.isOpen = false;
    });
  }
};
```

**Comment by cokuyan** [comment]
I had the same problem and got around it using jQuery to find the right element's scope. If you notice, the element actually inherits the isOpen property from its parent scope, so you have to change that value for it to work. But for some reason, the normal triggers didn't work so I made my own.
I put this method on the input field with an ngClick directive:
$scope.openDatepicker = function (index) {
  index = index || 0; // in case you have multiple inputs for the datepicker
  var datepickerScope = angular.element($('div[datepicker]')[index]).scope().$parent;
  datepickerScope.isOpen = true;
}
You don't need to worry about $apply since the ngClick should have fired in the correct scope.

**Comment by SDries** [comment]
Great! this works, thank you very much.
