### ISSUE TITLE
firefox xeditable input & buttons missing

### ISSUE THREAD

**Issue by map7** [vitalets/angular-xeditable#355]
If I use xeditable within a table 'td' tag then it works in chromium but not in firefox (version 38)

```
        <td editable-text="version.from_date"
            onbeforesave="update_version(level.id, version.id, $data, version.cost_cents)"
            class='date'>{{version.from_date}}</td>
```

If I put it within a span, it works fine.

```
        <td>
          <span editable-text="version.from_date"
              onbeforesave="update_version(level.id, version.id, $data, version.cost_cents)"
              class='date'>{{version.from_date}}</span>
        </td>
```

**Comment by gabrieleciech** [comment]
I'm experiencing the same behaviour, How can we investigate more on the problem?

**Comment by wayjake** [comment]
If you use an <a> tag as the root of the editable text it started working fine in Firefox. Couldn't figure out how to get the <td> going with it.

**Comment by starforgelabs** [comment]
Today I've run into the same issue with Firefox. Chrome and Safari work fine on <td> tags. 

The work-around of moving the editable-* attributes to a <span> withing the <td> appears to work. Thanks for the suggestion, @map7 . 

(All versions current as of 25 Jan 2017.)

**Comment by ckosloski** [comment]
The reason a td doesn't work is because the code tries to hide the text when the input field is shown.  Since the td contains both the text and the input field, the td ends up being hidden which then messes things up.
The documentation does state that editable-elements should be placed inside table cells.
This is working as intended and can be closed.

**Comment by ckosloski** [comment]
@eugef please close
