### ISSUE TITLE
Is it possible to edit the data in onbeforesave or anywhere else ?

### ISSUE THREAD

**Issue by GBora** [vitalets/angular-xeditable#391]
I have a x-editable in which the user is supposed to be able to  enter a list of names separated by a comma, so aaa,bbb,ccc and onbeforesave works well for me to validate the names so aaa,,,,bbb will be detected as bad as there's empty spaces where names should be.

I want to take it a bit further so that aaa,,,,bbb will be automatically trimmed to aaa,bbb which will be then evaluated.

So is it possible to change the value the user imputs automatically in onbeforesave ?

I've tried stuff like `data=properData` but in the UI the initial user data is always show and never the values I assigned.

**Comment by gabrieleciech** [comment]
@GBora I have a similar problem, did you find any solution?

**Comment by GBora** [comment]
@gabrieleciech I did not, ultimately I had to run a extra filtering function before I sent my model to the server, the user then saw the sanitised list after the server responded.

**Comment by mitcht** [comment]
Questions such as this are better suited to be posted on sites like stackoverflow.com, using their Q/A format. Thanks.

**Comment by gtarsia** [comment]
I accomplished this by including the actual row I want to update like this:  
`onbeforesave="updateUser($data, row)"`  

The problem is that in the body of `updateUser`, `row` is not updated yet. So you can get to that post-updated point with a `setTimeout` like this:
```js
function updateUser($data, row) {
  setTimeout(function() {
    row.whatever = <actual value>
  }, 0)
}
```
You can put that `setTimeout` after the last `then` of a `Promise` as well.
