### ISSUE TITLE
Opening another x-editable doesn't cause the current x-editable to blur

### ISSUE THREAD

**Issue by jlebrech** [vitalets/angular-xeditable#446]
When I open another x-editable i'd like it to save the current one and open the new one in edit mode.

Currently to do blur="save" the user has to click elsewhere than another x-editable.

If there's a workaround to cause other elements to blur when I open one I'll do that.

**Comment by johngomersall** [comment]
I'm new to x-editable and noticed this too.  I fixed it by commenting out the e.PreventDefault() line towards the end of editableDirectiveFactory (line 129 of the [source](https://github.com/vitalets/angular-xeditable/blob/master/src/js/editable-element/directive.js) or line 962 of the [un-minified distribution](https://github.com/vitalets/angular-xeditable/blob/master/dist/js/xeditable.js)).

Could figure out a way of changing the behaviour without changing the code though...

**Comment by ckosloski** [comment]
What version are you having the issue in?

**Comment by johngomersall** [comment]
I tried it with the Master at the time I posted my comment but looks like the lines have moved since then.  Haven't tried on the latest Master

**Comment by edmedo** [comment]
This remains an issue with 0.2.0. I've forked will attempt to work on a solution for this using https://github.com/vitalets/angular-xeditable/pull/311 as a base.

**Comment by edmedo** [comment]
Ok, this occurs if you apply `stopPropagation` to any of the editable wrappers or elements. This was required for me due to other events firing attached to elements below the editables.

**Comment by wetternest** [comment]
edmedo: which version of angular-xeditable did you use?

**Comment by jjreicher** [comment]
any updates on this issue? I see there was a fix in #311 but that was with version 0.1.x not with 0.2.0. Hoping someone has figured out how to fix this in 0.2.0.

For me the issue arises in making the app accessibility work correctly. With tabindex and editableOptions.activationEvent = 'focus'; I have been able to get the fields to activate by tabbing to them, but I cannot get them to save when I tab out--it should work as part of the blur="submit" but does not seem to. So I'm left with blur="cancel" or blur="ignore", neither of which are great solutions.

**Comment by ckosloski** [comment]
I think that blur="submit" only blurs on a click, so there needs to be a change to support something other than click.

**Comment by jjreicher** [comment]
Certainly seems to be true--you see the issue though, yes? Basically
conceptually tabbing away from the field should cause the field to "lose
focus" but blur doesn't seem to do that. Thought maybe focusout or
something along those lines might solve the problem.... Thoughts?

On Dec 7, 2016 4:26 PM, "ckosloski" <notifications@github.com> wrote:

I think that blur="submit" only blurs on a click, so there needs to be a
change to support something other than click.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/vitalets/angular-xeditable/issues/446#issuecomment-265616919>,
or mute the thread
