### ISSUE TITLE
Doesn't like dynamic Ids

### ISSUE THREAD

**Issue by fatboyslimfast** [vitalets/angular-xeditable#528]
Bit of a AngularJS newbie, but I'm looping through a JSON array and effectively creating one 'editable' table per row. 

I'm embedding the $index value in the name of the table e.g. e-form="componentTableForm_{{$index}}" form e.g.  editable-form name="componentTableForm_{{$index}}"  and buttons - <button type="button" class="btn btn-default"
                                ng-show="!componentTableForm_{{$index}}.$visible"
                                ng-click="componentTableForm_{{$index}}.$show()">
                                edit</button>

I'm getting angular.js errors  - 

> Syntax Error: Token '{' is an unexpected token 

So my question is, does angular-xeditable support this kind of implementation?

**Comment by ckosloski** [comment]
Your issue is with angular and not with xeditable.  The issue is with the ng-show and ng-click.
I think you need to create functions to pass in the name values and eval it in the function.
`showForm('componentTableForm_', $index)`
`showForm('componentTableForm_', $index)`

Not 100% sure on the correct solution though.

**Comment by ckosloski** [comment]
@fatboyslimfast are you still having an issue?

**Comment by ckosloski** [comment]
@eugef Please close due to lack of response.
