### ISSUE TITLE
Edit form in AngularUi Tab Heading doesn't react to mouse click

### ISSUE THREAD

**Issue by Piastr** [vitalets/angular-xeditable#563]
I use xeditable in AngularUI Tab.
```
<uib-tab-heading>
    <span editable-text="heading1" buttons="no" blur="submit" e-form="textBtnForm1" ng-dblclick="textBtnForm1.$show()">{{ heading1 || 'empty' }}</span>
</uib-tab-heading>
```
The submit button on the edit form didn't work so I used this [solution](https://github.com/vitalets/angular-xeditable/issues/107#issuecomment-82363331)

But I still have another problem: mouse don't work inside edit form. Text coursor isn't set on mouse click and text isn't selected by mouse.

[Plunker example](https://plnkr.co/edit/936qIxyFJIvVkRQT2Mz7?p=preview)

**Comment by ckosloski** [comment]
Did you see the Known Issues section of [ui-tabs](http://angular-ui.github.io/bootstrap/#/tabs)?  Could be the issue:

> Known issues
To use clickable elements within the tab, you have override the tab template to use div elements instead of anchor elements, and replicate the desired styles from Bootstrap's CSS. This is due to browsers interpreting anchor elements as the target of any click event, which triggers routing when certain elements such as buttons are nested inside the anchor element.

**Comment by Piastr** [comment]
Mea culpa.
Thanks, it works.

```
<uib-tab index="0" template-url="mytab.html">
   <uib-tab-heading>
      <span editable-text="heading1" buttons="no" blur="submit" e-form="textBtnForm1" ng-dblclick="textBtnForm1.$show()">{{ heading1 || 'empty' }}</span>
     </uib-tab-heading>
      content 1
</uib-tab>

<script type="text/ng-template" id="mytab.html">
   <li ng-class="[{active: active, disabled: disabled}, classes]" class="uib-tab nav-item">
      <div href ng-click="select($event)" class="nav-link" uib-tab-heading-transclude>{{heading}}</div>
   </li>
</script>
```

**Comment by LegendOfFire** [comment]
Thank you! It's solved.
